import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, Bot, CheckCircle2, Languages, Map, MapPinned, Network, Route, Search, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { AI_CAPABILITIES, AI_EXAMPLE_PROMPTS, AI_GUARDRAILS, AI_PRINCIPLE, SOURCE_TYPES } from '../data/aiHeritage'

const iconMap = { Sparkles, Search, Route, Languages, Network, MapPinned, Map, GitCompare: Network }

export default function AIHeritage(){
  const navigate = useNavigate()
  const openGuide = (prompt='') => { navigate('/'); setTimeout(() => window.dispatchEvent(new CustomEvent('open-heritage-guide', { detail: { prompt } })), 80) }
  return <main className="content-page">
    <section className="relative overflow-hidden bg-maroon text-cream">
      <div className="absolute -left-16 top-10 h-72 w-72 rounded-full bg-gold/15 blur-3xl"/>
      <div className="absolute right-0 bottom-0 h-80 w-80 rounded-full bg-saffron/10 blur-3xl"/>
      <div className="relative mx-auto max-w-7xl px-4 py-16 md:px-8 md:py-24">
        <div className="max-w-4xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-[10px] font-bold uppercase tracking-[.22em] text-gold"><Bot size={14}/> AI + Heritage</div>
          <h1 className="mt-6 font-display text-5xl leading-[.96] sm:text-6xl lg:text-8xl">A smarter way to<br/><span className="text-gold">discover heritage.</span></h1>
          <p className="mt-6 max-w-2xl text-base leading-7 text-cream/70 md:text-lg">Use conversational AI to explore the cultural atlas, shape heritage journeys, compare traditions and connect places with living cultural practice — while keeping human knowledge and community context at the centre.</p>
          <div className="mt-8 rounded-[1.75rem] border border-white/10 bg-white/5 p-5 shadow-warm"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-gold">Our principle</div><div className="mt-2 font-display text-2xl md:text-3xl">{AI_PRINCIPLE}</div></div>
          <div className="mt-7 flex flex-wrap gap-3"><button onClick={() => openGuide('Show me cultural traditions near Mysuru.')} className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-bold text-ink hover:-translate-y-0.5"><Sparkles size={15}/> Ask the Heritage Guide</button><Link to="/#atlas" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white hover:bg-white/5"><Map size={15}/> Explore the atlas</Link></div>
        </div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-4 py-14 md:px-8 md:py-20">
      <div className="max-w-2xl"><div className="text-xs font-bold uppercase tracking-[.2em] text-maroon/60">What the AI layer does</div><h2 className="mt-2 font-display text-4xl text-ink md:text-5xl">Conversation around the cultural map.</h2><p className="mt-4 text-sm leading-6 text-ink/55">The assistant complements the atlas instead of replacing it. Every planning response can point users back to the map, state, district, tradition or trail behind the suggestion.</p></div>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{AI_CAPABILITIES.map((item)=>{const Icon=iconMap[item.icon]||Sparkles; return <article key={item.id} className="rounded-[1.5rem] border border-maroon/10 bg-white p-5 shadow-card transition hover:-translate-y-1 hover:shadow-warm"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-saffron/10 text-maroon"><Icon size={19}/></div><h3 className="mt-4 font-display text-2xl text-maroon">{item.title}</h3><p className="mt-2 text-sm leading-6 text-ink/55">{item.body}</p></article>})}</div>
    </section>

    <section className="border-y border-maroon/10 bg-white/60"><div className="mx-auto max-w-7xl px-4 py-14 md:px-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-maroon/60">Ask naturally</div><h2 className="mt-2 font-display text-4xl text-ink md:text-5xl">Try the guide with real questions.</h2></div><Link to="/?openGuide=1" className="inline-flex items-center gap-2 self-start rounded-full bg-maroon px-5 py-3 text-sm font-bold text-white">Open guide <ArrowRight size={15}/></Link></div><div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{AI_EXAMPLE_PROMPTS.map((prompt)=><button key={prompt} onClick={() => openGuide(prompt)} className="group w-full text-left rounded-2xl border border-maroon/10 bg-cream p-4 transition hover:-translate-y-0.5 hover:shadow-card"><div className="flex items-start gap-3"><span className="mt-0.5 grid h-8 w-8 place-items-center rounded-xl bg-maroon text-gold"><Search size={14}/></span><span className="text-sm leading-6 text-ink/75">{prompt}</span></div><div className="mt-3 inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-[.14em] text-maroon/55">Ask the guide <ArrowRight size={11}/></div></button>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 md:px-8 md:py-20"><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-9"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-teal-50 text-teal-700"><ShieldCheck size={20}/></div><div><div className="text-xs font-bold uppercase tracking-[.18em] text-teal-700">Trust layer</div><h2 className="font-display text-3xl text-maroon">Know what you’re seeing.</h2></div></div><div className="mt-7 space-y-3">{Object.entries(SOURCE_TYPES).map(([key,item])=><div key={key} className="flex items-start gap-3 rounded-2xl border border-maroon/10 bg-cream p-4"><span className={`mt-0.5 rounded-full px-2.5 py-1 text-[9px] font-bold ${item.tone==='green'?'bg-teal-50 text-teal-700':item.tone==='gold'?'bg-gold/20 text-maroon':'bg-maroon text-white'}`}>{item.label}</span><p className="text-sm leading-6 text-ink/60">{item.description}</p></div>)}</div></div><div className="rounded-[2rem] bg-[#242424] p-7 text-cream shadow-warm md:p-9"><div className="flex items-center gap-3"><Users size={21} className="text-gold"/><div className="text-xs font-bold uppercase tracking-[.18em] text-gold">Safeguards</div></div><h2 className="mt-4 font-display text-3xl">Human knowledge stays in charge.</h2><div className="mt-6 space-y-3">{AI_GUARDRAILS.map((rule,i)=><div key={rule} className="flex gap-3 text-sm leading-6 text-cream/65"><CheckCircle2 size={16} className="mt-1 shrink-0 text-gold"/><span>{rule}</span></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-4 pb-16 md:px-8"><div className="rounded-[2rem] border border-maroon/10 bg-gradient-to-br from-[#F7F1E3] to-white p-7 shadow-card md:p-10"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/60">Keep exploring</div><h2 className="mt-2 font-display text-4xl text-maroon">From a question back to the map.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/55">Use the AI guide to ask, then return to the geographic atlas to inspect the state, district and tradition behind the answer.</p></div><Link to="/#atlas" className="inline-flex items-center gap-2 rounded-full bg-maroon px-5 py-3 text-sm font-bold text-white">Open cultural atlas <MapPinned size={15}/></Link></div></div></section>
  </main>
}
