import { useMemo, useState } from 'react'
import { ArrowLeft, Bookmark, Check, HeartHandshake, MapPinned, PlayCircle, Plus, ShoppingBag, Sparkles, Ticket, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import ImpactActions from '../components/ImpactActions'
import { craftById, CRAFTS } from '../data/crafts'

const ACTIONS=[['LEARN','Learn',Sparkles],['WATCH','Watch',PlayCircle],['VISIT','Visit',MapPinned],['BUY','Buy responsibly',ShoppingBag],['SUPPORT','Support',HeartHandshake]]
export default function CraftDetail(){
 const {craftId=''}=useParams(); const craft=craftById[craftId]; const [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('savedCrafts')||'[]').includes(craftId)); const [added,setAdded]=useState(false)
 const similar=useMemo(()=>craft?CRAFTS.filter(c=>c.id!==craft.id&&(c.state===craft.state||c.type===craft.type)).slice(0,3):[],[craft])
 if(!craft)return <main className="content-page mx-auto max-w-4xl px-4 py-20"><div className="rounded-[2rem] bg-white p-10 text-center shadow-card"><h1 className="font-display text-4xl text-maroon">Craft profile coming soon</h1><Link to="/crafts" className="mt-6 inline-flex rounded-full bg-maroon px-5 py-3 text-sm font-bold text-white">Back to craft discovery</Link></div></main>
 const toggleSave=()=>{const next=saved?JSON.parse(localStorage.getItem('savedCrafts')||'[]').filter(x=>x!==craftId):[...JSON.parse(localStorage.getItem('savedCrafts')||'[]'),craftId];localStorage.setItem('savedCrafts',JSON.stringify(next));setSaved(!saved)}
 return <main>
  <section className="relative overflow-hidden bg-maroon text-cream"><div className="absolute inset-0 ornament opacity-15"/><div className="relative mx-auto max-w-7xl px-4 py-12 md:px-8 md:py-16"><Link to="/crafts" className="inline-flex items-center gap-2 rounded-full border border-gold/20 px-4 py-2 text-xs font-bold text-gold"><ArrowLeft size={14}/> Craft discovery</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-gold">{craft.type}</div><h1 className="mt-3 font-display text-5xl leading-none md:text-7xl">{craft.name}</h1><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-1.5">{craft.state}</span><span className="rounded-full bg-white/10 px-3 py-1.5">{craft.district}</span><span className="rounded-full bg-white/10 px-3 py-1.5 inline-flex items-center gap-1"><Users size={12}/> {craft.community}</span></div></div><img src={craft.image} alt={`Representative image for ${craft.name}`} className="h-72 w-full rounded-[2rem] object-cover shadow-2xl"/></div><div className="mt-7 flex flex-wrap gap-3"><button onClick={toggleSave} className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-bold text-ink">{saved?<Check size={16}/>:<Bookmark size={16}/>} {saved?'Saved':'Save Tradition'}</button><button onClick={()=>setAdded(true)} className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white"><Plus size={16}/> {added?'Added to trail':'Add to Heritage Trail'}</button><button onClick={()=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(craft.place+', India')}`,'_blank')} className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white"><MapPinned size={16}/> Explore on Map</button></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-12 md:px-8 md:py-16"><div className="grid gap-7 lg:grid-cols-[1fr_.7fr]"><div className="space-y-6">
   <article className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-9"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-maroon/60">01 • What is it?</div><p className="mt-4 text-lg leading-8 text-ink/70">{craft.intro}</p></article>
   <article className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-9"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-maroon/60">02 • Where is it practiced?</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-cream p-4"><div className="text-[10px] uppercase tracking-widest text-ink/40">State</div><div className="mt-1 font-bold text-maroon">{craft.state}</div></div><div className="rounded-2xl bg-cream p-4"><div className="text-[10px] uppercase tracking-widest text-ink/40">District</div><div className="mt-1 font-bold text-maroon">{craft.district}</div></div><div className="rounded-2xl bg-cream p-4"><div className="text-[10px] uppercase tracking-widest text-ink/40">Town / region</div><div className="mt-1 font-bold text-maroon">{craft.place.split(',')[0]}</div></div></div></article>
   <article className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-9"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-maroon/60">03 • Who practices it?</div><div className="mt-4 flex items-start gap-3 rounded-2xl bg-cream p-5"><Users className="mt-1 text-maroon" size={19}/><p className="text-sm leading-6 text-ink/65">{craft.community}. This profile uses a broad community description where more specific practitioner attribution is not responsibly available.</p></div></article>
   <article className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-9"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-maroon/60">04 • History & origins</div><p className="mt-4 text-sm leading-7 text-ink/65">{craft.history}</p></article>
   <article className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-9"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-maroon/60">05 • How is it made?</div><p className="mt-4 text-sm leading-7 text-ink/65"><b>Materials:</b> {craft.materials}</p><div className="mt-5 grid gap-3 md:grid-cols-2">{craft.process.map((s,i)=><div key={s} className="flex gap-3 rounded-2xl bg-cream p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-maroon text-xs font-bold text-white">{i+1}</span><span className="text-sm leading-6 text-ink/65">{s}</span></div>)}</div></article>
   <ImpactActions item={craft} title="Take the next step"/>
  </div><aside className="space-y-5 lg:sticky lg:top-24 lg:self-start"><div className="rounded-[2rem] border border-maroon/10 bg-white p-6 shadow-card"><div className="font-display text-2xl text-maroon">The practice comes first.</div><p className="mt-3 text-sm leading-6 text-ink/55">Explore this craft through knowledge, people and place before considering a purchase.</p><div className="mt-5 grid gap-2">{[['Learn',craft.learn,Sparkles],['Watch',craft.watch,PlayCircle],['Visit',craft.visit,MapPinned],['Buy responsibly',craft.buy,ShoppingBag],['Support',craft.support,HeartHandshake]].map(([t,body,I])=><div key={t} className="rounded-2xl border border-maroon/10 bg-cream p-4"><div className="flex items-center gap-2 text-sm font-bold text-maroon"><I size={15}/>{t}</div><p className="mt-1 text-xs leading-5 text-ink/55">{body}</p></div>)}</div></div><div className="rounded-[2rem] bg-maroon p-6 text-cream"><div className="text-xs font-bold uppercase tracking-[.18em] text-gold">Source note</div><p className="mt-3 text-sm leading-6 text-cream/70">Primary profile source: {craft.source}.</p><a href={craft.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-gold">Open source ↗</a></div></aside></div>
   {similar.length>0&&<section className="mt-14"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-maroon/60">Find similar traditions</div><h2 className="mt-2 font-display text-4xl text-maroon">Continue exploring</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{similar.map(x=><Link key={x.id} to={`/craft/${x.id}`} className="rounded-[1.6rem] border border-maroon/10 bg-white p-5 shadow-card hover:-translate-y-1 hover:shadow-warm"><div className="text-xs font-bold uppercase tracking-wider text-maroon/55">{x.type}</div><div className="mt-2 font-display text-2xl text-maroon">{x.name}</div><div className="mt-2 text-xs text-ink/45">{x.place}</div></Link>)}</div></section>}
  </section>
 </main>
}
