import { useMemo, useState } from 'react'
import { ArrowRight, Filter, HeartHandshake, MapPinned, Search, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CRAFTS } from '../data/crafts'
import { useLanguage } from '../components/LanguageContext'

export default function Crafts(){
 const { t } = useLanguage()
 const [q,setQ]=useState(''); const [state,setState]=useState('All'); const [type,setType]=useState('All')
 const states=['All',...Array.from(new Set(CRAFTS.map(c=>c.state))).sort()]
 const types=['All',...Array.from(new Set(CRAFTS.map(c=>c.type))).sort()]
 const items=useMemo(()=>CRAFTS.filter(c=>(!q||`${c.name} ${c.place} ${c.community} ${c.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase()))&&(state==='All'||c.state===state)&&(type==='All'||c.type===type)),[q,state,type])
 return <main className="content-page">
  <section className="relative overflow-hidden bg-maroon text-cream"><div className="absolute inset-0 heritage-grid opacity-20"/><div className="relative mx-auto max-w-7xl px-4 py-16 md:px-8 md:py-20"><div className="max-w-4xl"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-gold"><Sparkles size={14}/> {t.crafts}</div><h1 className="mt-4 font-display text-5xl leading-none md:text-7xl">Meet the hands,<br/><span className="text-gold">not just the object.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-cream/65">Explore Indian crafts through the people, places, techniques and knowledge that keep them alive. Products are one outcome; the practice comes first.</p></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-10 md:px-8"><div className="rounded-[2rem] border border-maroon/10 bg-white p-5 shadow-card md:p-6"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto]"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-maroon/45" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a craft, place, community…" className="w-full rounded-2xl border border-maroon/10 bg-cream py-3 pl-11 pr-4 text-sm outline-none focus:border-maroon/25"/></div><select value={state} onChange={e=>setState(e.target.value)} className="rounded-2xl border border-maroon/10 bg-cream px-4 py-3 text-sm"><option>All</option>{states.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-2xl border border-maroon/10 bg-cream px-4 py-3 text-sm"><option>All</option>{types.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-4 flex items-center gap-2 text-xs text-ink/45"><Filter size={14}/> {items.length} craft profiles • curated with source notes</div></div>
  <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(c=><article key={c.id} className="group overflow-hidden rounded-[2rem] border border-maroon/10 bg-white shadow-card hover:-translate-y-1 hover:shadow-warm"><div className="relative h-52 overflow-hidden bg-cream"><img src={c.image} alt={`Representative visual for ${c.name}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-maroon">{c.type}</div></div><div className="p-6"><h2 className="font-display text-3xl text-maroon">{c.name}</h2><div className="mt-2 flex flex-wrap gap-2 text-xs text-ink/50"><span className="inline-flex items-center gap-1"><MapPinned size={12}/> {c.place}</span><span className="inline-flex items-center gap-1"><Users size={12}/> {c.community}</span></div><p className="mt-4 text-sm leading-6 text-ink/58">{c.intro}</p><Link to={`/craft/${c.id}`} className="mt-5 inline-flex items-center gap-2 rounded-full bg-maroon px-4 py-2.5 text-xs font-bold text-white hover:-translate-y-0.5">Explore craft <ArrowRight size={14}/></Link></div></article>)}</div>{!items.length&&<div className="py-20 text-center text-sm text-ink/45">No craft profile matches those filters yet.</div>}</section>
  <section className="mx-auto max-w-7xl px-4 pb-16 md:px-8"><div className="rounded-[2rem] bg-cream p-8 md:p-10"><div className="text-xs font-bold uppercase tracking-[.2em] text-maroon/60">A respectful path</div><div className="mt-3 grid gap-4 md:grid-cols-4"><div><b className="text-maroon">1. Learn</b><p className="mt-1 text-sm leading-6 text-ink/55">Understand technique and context.</p></div><div><b className="text-maroon">2. Meet</b><p className="mt-1 text-sm leading-6 text-ink/55">Follow the people and places behind the practice.</p></div><div><b className="text-maroon">3. Participate</b><p className="mt-1 text-sm leading-6 text-ink/55">Visit, watch or learn with consent and care.</p></div><div><b className="text-maroon">4. Support</b><p className="mt-1 text-sm leading-6 text-ink/55">Prefer transparent, community-linked pathways.</p></div></div></div></section>
 </main>
}
