import { useState } from 'react'
import { ArrowRight, Landmark, Music, Palette, Shirt, Sparkles, Utensils, XCircle } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { regionBySlug, stateData } from '../data/states'
import { stateVisuals } from '../data/stateVisuals'
import { regionalLanguages } from '../data/regionalLanguages'
import { regionalUi, regionalStateCopy, regionalPhrases } from '../data/regionalContent'
import ImpactActions from '../components/ImpactActions'
import { useLanguage } from '../components/LanguageContext'
import { LANGUAGES } from '../data/i18n'

const tabs=[['Overview','overview',Sparkles],['Dress','dress',Shirt],['Festivals','festivals',Sparkles],['Dance & Music','dance',Music],['Cuisine','cuisine',Utensils],['Arts & Crafts','crafts',Palette],['Monuments','monuments',Landmark]]
const translatedTabKey={overview:'overview',dress:'dress',festivals:'festivals',dance:'dance',cuisine:'cuisine',crafts:'crafts',monuments:'monuments'}
function ListCard({title,text,icon,impact=false,state,district,type}){const Icon=icon; return <div className="group rounded-3xl border border-maroon/10 bg-white p-5 shadow-card transition hover:-translate-y-1 hover:shadow-warm"><div className="flex items-start justify-between gap-4"><h3 className="font-display text-2xl text-ink">{title}</h3>{Icon&&<span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-saffron/10 text-maroon"><Icon size={16}/></span>}</div><p className="mt-3 text-sm leading-6 text-ink/60">{text}</p>{impact&&<ImpactActions item={{name:title,state,district,type}} compact/>}</div>}

function Missing({name}){return <main className="content-page mx-auto max-w-4xl px-4 py-20 md:px-8"><div className="rounded-[2rem] border border-maroon/10 bg-white p-8 text-center shadow-warm md:p-14"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-saffron/10 text-maroon"><XCircle/></div><div className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-maroon/65">Profile unavailable</div><h1 className="mt-2 font-display text-5xl">{name}</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-ink/55">Content coming soon. This route is intentionally safe: a missing JSON file never crashes the application.</p><div className="mt-8 flex justify-center gap-3"><Link to="/" className="inline-flex items-center gap-2 rounded-full bg-maroon px-5 py-3 text-sm font-bold text-white">Back home <ArrowRight size={15}/></Link><Link to="/compare" className="inline-flex items-center gap-2 rounded-full border border-maroon/15 px-5 py-3 text-sm font-bold text-maroon">Compare states</Link></div></div></main>}

export default function StateDetail(){
 const {stateName=''}=useParams(); const { language, t: globalT, active } = useLanguage(); const canonical=regionBySlug[stateName] || stateName.split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' '); const data=stateData[stateName]; const visual=stateVisuals[stateName]; const locale=regionalLanguages[stateName]; const copy=regionalStateCopy[stateName]; const ui=regionalUi[stateName]; const phrases=regionalPhrases[stateName]; const [tab,setTab]=useState('overview'); const regionalCode = ui?.lang; const regional = language===regionalCode; const localizedAvailable = regional && !!copy;
 if(!data) return <Missing name={canonical}/>
 const L=regional && ui ? ui.labels : {profile:'Cultural profile',overview:'Overview',dress:'Dress',festivals:'Festivals',dance:'Dance & Music',cuisine:'Cuisine',crafts:'Arts & Crafts',monuments:'Monuments',folklore:'Folklore & memory',capital:'Capital',languages:'Languages',regional:'Regional language',men:'Men',women:'Women',textile:'Textile notes',danceLabel:'Dance',musicLabel:'Music'};
 const displayState=regional && copy ? copy.state : data.state;
 const displayCapital=regional && copy ? copy.capital : data.capital;
 const dress=regional && copy ? copy.dress : data.traditionalDress;
 const festivals=regional && copy ? copy.festivals.map(([name,description])=>({name,description})) : data.festivals;
 const folklore=regional && copy ? copy.folklore : data.folklore;
 return <main lang={regional && ui ? ui.lang : 'en'}>
  <section className="relative overflow-hidden bg-maroon text-cream"><div className="absolute inset-0 opacity-20 ornament"/><div className="relative mx-auto max-w-7xl px-4 pb-12 pt-14 md:px-8 md:pb-16 md:pt-20"><div className="flex flex-wrap items-center justify-between gap-3"><div className="text-xs font-bold uppercase tracking-[.22em] text-gold">{L.profile} · {displayCapital}</div>{ui&&<button type="button" aria-pressed={regional} onClick={()=>{ localStorage.setItem('indian-heritage-last-state-language', stateName); window.dispatchEvent(new CustomEvent('open-language-picker')) }} className="inline-flex items-center gap-2 rounded-full border border-gold/40 bg-gold/10 px-4 py-2 text-xs font-bold text-gold shadow-lg transition hover:-translate-y-0.5 hover:bg-gold/20">{regional ? 'EN · English' : (ui?.short || active.native) + ' · ' + (ui?.viewRegional || globalT.change)}</button>}</div><div className="mt-3 flex flex-wrap items-end gap-x-4 gap-y-2"><h1 className="font-display text-5xl md:text-7xl">{displayState}</h1>{locale&&<span className="pb-2 font-display text-3xl text-gold md:text-4xl" lang={ui?.lang || 'auto'}>{locale.nativeName}</span>}</div><p className="mt-5 max-w-2xl text-base leading-7 text-cream/70">{regional && phrases ? phrases.tagline : 'A field guide to language, celebration, performance, food, craft, folklore and monuments.'}</p>{!regional && language!=='en' && <div className="mt-3 inline-flex rounded-full border border-gold/25 bg-gold/10 px-3 py-1.5 text-[11px] font-semibold text-gold">{globalT.sourceNote}</div>}<div className="mt-7 flex flex-wrap gap-2">{data.languages.slice(0,4).map(x=><span key={x} className="rounded-full border border-cream/15 bg-white/5 px-3 py-1 text-xs text-cream/75">{x}</span>)}{locale&&<span className="rounded-full border border-gold/30 bg-gold/10 px-3 py-1 text-xs font-semibold text-gold" lang={ui?.lang || 'auto'}>{locale.languageName} · {locale.englishLanguage}</span>}</div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-8 md:px-8"><div className="sticky top-[72px] z-30 overflow-x-auto rounded-2xl border border-maroon/10 bg-cream/90 p-1.5 shadow-card backdrop-blur-xl"><div className="flex min-w-max gap-1">{tabs.map(([label,key,Icon])=>{const localized={overview:L.overview,dress:L.dress,festivals:L.festivals,dance:L.dance,cuisine:L.cuisine,crafts:L.crafts,monuments:L.monuments}[key]; return <button key={key} onClick={()=>setTab(translatedTabKey[key])} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===key?'bg-maroon text-white shadow-md':'text-ink/55 hover:bg-maroon/5 hover:text-maroon'}`}><Icon size={15}/>{regional?localized:label}</button>})}</div></div>
   <div className="mt-10 min-h-[360px] animate-fadeUp">
    {tab==='overview'&&<div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-maroon/10 bg-white p-7 shadow-card"><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/65">{L.folklore}</div><p className="story-dropcap mt-5 text-lg leading-8 text-ink/75">{folklore}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><ListCard title={L.capital} text={displayCapital}/><ListCard title={L.languages} text={data.languages.join(' • ')}/>{locale&&<ListCard title={L.regional} text={`${locale.languageName} (${locale.englishLanguage})`}/>}</div></div>}
    {tab==='dress'&&<div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="relative flex min-h-72 items-end overflow-hidden rounded-[2rem] bg-gradient-to-br from-saffron/30 to-maroon/10 p-7 shadow-warm"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/65">{L.textile}</div><h2 className="mt-2 font-display text-4xl">{regional ? 'ಉಡುಪು ಮತ್ತು ಗುರುತು' : 'Dress as identity'}</h2><p className="mt-3 max-w-md text-sm leading-6 text-ink/60">{regional && phrases ? phrases.dress : 'Traditional clothing reflects climate, craft practices, ceremony and regional identity.'}</p></div>{visual&&<img src={visual.image} alt={`Traditional ${data.state} cultural scene showing ${visual.theme}`} className="absolute -right-2 -top-4 h-44 w-44 rotate-3 rounded-3xl object-cover opacity-90 shadow-xl" onError={e=>{e.currentTarget.src=visual.fallback}}/>}</div><div className="grid gap-4"><ListCard title={L.men} text={dress.men} icon={Shirt}/><ListCard title={L.women} text={dress.women} icon={Shirt}/></div></div>}
    {tab==='festivals'&&<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{festivals.map((x,i)=><div key={x.name} className="rounded-3xl border border-maroon/10 bg-white p-6 shadow-card transition hover:-translate-y-1 hover:shadow-warm"><div className="text-xs font-bold uppercase tracking-[.18em] text-gold">0{i+1}</div><h3 className="mt-3 font-display text-2xl">{x.name}</h3><p className="mt-3 text-sm leading-6 text-ink/60">{x.description}</p><ImpactActions item={{name:x.name,state:data.state,type:'Festivals'}} compact/></div>)}</div>}
    {tab==='dance'&&<div className="grid gap-8 lg:grid-cols-2"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/65">{L.danceLabel}</div><div className="mt-4 grid gap-3">{data.danceForms.map(x=><div key={x} className="rounded-2xl border border-maroon/10 bg-white px-5 py-4 font-semibold shadow-card"><div>{x}</div><ImpactActions item={{name:x,state:data.state,type:'Dance & Music'}} compact/></div>)}</div></div><div><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/65">{L.musicLabel}</div><div className="mt-4 grid gap-3">{data.music.map(x=><div key={x} className="rounded-2xl border border-maroon/10 bg-white px-5 py-4 font-semibold shadow-card"><div>{x}</div><ImpactActions item={{name:x,state:data.state,type:'Music'}} compact/></div>)}</div></div></div>}
    {tab==='cuisine'&&<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.cuisine.map(x=><ListCard key={x} title={x} text={regional && phrases ? phrases.cuisine : "A representative part of the region's food culture."} icon={Utensils} impact state={data.state} type="Food"/>)}</div>}
    {tab==='crafts'&&<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.artsCrafts.map(x=><ListCard key={x} title={x} text={regional && phrases ? phrases.craft : "A documented craft or textile tradition associated with the state."} icon={Palette} impact state={data.state} type="Traditional Crafts"/>)}</div>}
    {tab==='monuments'&&<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.monuments.map((x)=><div key={x} className="rounded-3xl border border-maroon/10 bg-gradient-to-br from-white to-saffron/5 p-6 shadow-card transition hover:-translate-y-1 hover:shadow-warm"><div className="grid h-10 w-10 place-items-center rounded-full bg-maroon text-gold"><Landmark size={18}/></div><h3 className="mt-5 font-display text-2xl">{x}</h3><p className="mt-2 text-sm text-ink/50">{regional && phrases ? phrases.monument : `Heritage landmark • ${data.state}`}</p><ImpactActions item={{name:x,state:data.state,type:'Heritage Sites'}} compact/></div>)}</div>}
   </div>
  </section>
 </main>
}
