import { ArrowLeft, Heart, MapPin, Sparkles } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import ImpactActions from '../components/ImpactActions'
import { traditionById } from '../data/traditions'

export default function TraditionDetail(){
 const {traditionId=''}=useParams(); const item=traditionById[traditionId]
 if(!item) return <main className="content-page mx-auto max-w-4xl px-4 py-20"><div className="rounded-[2rem] border border-maroon/10 bg-white p-10 text-center shadow-warm"><h1 className="font-display text-4xl">Tradition profile coming soon</h1><p className="mt-3 text-sm text-ink/55">This cultural profile has not yet been curated.</p><Link to="/" className="mt-6 inline-flex items-center gap-2 rounded-full bg-maroon px-5 py-3 text-sm font-bold text-white"><ArrowLeft size={15}/> Back to atlas</Link></div></main>
 return <main>
  <section className="relative overflow-hidden bg-maroon text-cream"><div className="absolute inset-0 ornament opacity-20"/><div className="relative mx-auto max-w-7xl px-4 py-16 md:px-8 md:py-20"><Link to="/#atlas" className="inline-flex items-center gap-2 rounded-full border border-gold/25 px-4 py-2 text-xs font-bold text-gold hover:bg-gold/10"><ArrowLeft size={14}/> Back to cultural atlas</Link><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-gold">{item.type}</div><h1 className="mt-3 font-display text-5xl leading-none md:text-7xl">{item.name}</h1><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{item.state}</span><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{item.district}</span><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{item.community}</span></div></div><img src={item.image} alt={`Representative visual for ${item.name}`} className="h-64 w-full rounded-[2rem] object-cover shadow-2xl lg:h-72"/></div></div></section>
  <section className="mx-auto grid max-w-7xl gap-6 px-4 py-12 md:px-8 md:py-16 lg:grid-cols-[1.1fr_.9fr]">
   <div className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card md:p-10"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-maroon/65"><Sparkles size={14}/> Cultural context</div><p className="mt-5 text-lg leading-8 text-ink/70">{item.summary}</p><div className="mt-8 rounded-3xl bg-cream p-6"><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/65">Why attention matters</div><p className="mt-3 text-sm leading-7 text-ink/60">{item.why}</p></div></div>
   <div className="grid gap-4"><div className="rounded-[2rem] border border-maroon/10 bg-white p-7 shadow-card"><div className="text-xs font-bold uppercase tracking-[.18em] text-maroon/65">Current status</div><div className="mt-3 inline-flex rounded-full bg-saffron/15 px-4 py-2 text-sm font-bold text-maroon">{item.status}</div><p className="mt-4 text-sm leading-6 text-ink/55">Status here is a presentation label for this atlas, not a claim of formal national classification.</p></div><Link to={`/state/${item.state.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`} className="inline-flex items-center justify-center gap-2 rounded-full border border-maroon/15 px-5 py-3 text-sm font-bold text-maroon hover:bg-maroon/5"><MapPin size={15}/> Explore {item.state}</Link></div>
  </section>
 </main>
}
