import { ArrowLeftRight } from 'lucide-react'

const rows = [
  ['Capital','capital'],['Languages','languages'],['Men’s dress','traditionalDress.men'],['Women’s dress','traditionalDress.women'],['Festivals','festivals'],['Dance forms','danceForms'],['Music','music'],['Cuisine','cuisine'],['Arts & crafts','artsCrafts'],['Folklore','folklore'],['Monuments','monuments']
]
function get(obj,path){return path.split('.').reduce((a,k)=>a?.[k],obj)}
function renderValue(value,key){ if(Array.isArray(value)) return <div className="flex flex-wrap gap-2">{value.map((v,i)=><span key={i} className="rounded-full bg-maroon/5 px-2.5 py-1 text-xs text-maroon">{typeof v==='string'?v:v.name}</span>)}</div>; if(key==='festivals') return <div className="space-y-2">{value.map((v,i)=><div key={i}><strong className="font-semibold">{v.name}</strong><p className="text-xs text-ink/60">{v.description}</p></div>)}</div>; return <span>{value}</span> }
export default function CompareView({ left, right, leftName, rightName }) {
  return <div className="overflow-x-auto rounded-3xl border border-maroon/10 bg-white shadow-card"><table className="min-w-[760px] w-full border-collapse"><thead><tr className="bg-ink text-cream"><th className="w-44 px-5 py-5 text-left text-xs uppercase tracking-[.16em] text-gold">Field</th><th className="px-5 py-5 text-left font-display text-2xl">{leftName || 'Select a state'}</th><th className="px-5 py-5 text-left font-display text-2xl">{rightName || 'Select a state'}</th></tr></thead><tbody>{rows.map(([label,key],i)=><tr key={key} className={i%2?'bg-cream/70':''}><th className="border-t border-maroon/10 px-5 py-5 text-left align-top text-sm font-semibold text-maroon">{label}</th><td className="border-t border-maroon/10 px-5 py-5 align-top text-sm leading-6">{left?renderValue(get(left,key),key):<span className="text-ink/30">—</span>}</td><td className="border-t border-maroon/10 px-5 py-5 align-top text-sm leading-6">{right?renderValue(get(right,key),key):<span className="text-ink/30">—</span>}</td></tr>)}</tbody></table><div className="flex items-center gap-2 border-t border-maroon/10 px-5 py-3 text-xs text-ink/50"><ArrowLeftRight size={14}/> Compare the same schema field by field.</div></div>
}
