import { Check, Globe2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useLanguage } from './LanguageContext'

export default function LanguageSelector({ compact=false }){
  const { language, setLanguage, languages, active, t } = useLanguage()
  const [open,setOpen]=useState(false)
  const [onboarding,setOnboarding]=useState(()=>!localStorage.getItem('indian-heritage-language'))
  useEffect(()=>{ if(language) document.documentElement.lang=language },[language])
  useEffect(()=>{ const handler=()=>setOpen(true); window.addEventListener('open-language-picker',handler); return ()=>window.removeEventListener('open-language-picker',handler)},[])
  const choose=(code)=>{setLanguage(code); setOpen(false); setOnboarding(false)}
  return <>
    <button onClick={()=>setOpen(true)} className={`inline-flex items-center gap-2 rounded-full border border-maroon/12 bg-white/90 px-4 py-2.5 text-xs font-bold text-maroon shadow-sm hover:-translate-y-0.5 hover:shadow-card ${compact?'px-3 py-2':''}`} aria-label={t.change}><Globe2 size={15}/><span>{compact?active.native:`${t.languages}: ${active.native}`}</span></button>
    {open&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-ink/30 p-3 backdrop-blur-sm sm:items-center" onMouseDown={()=>setOpen(false)}><div className="w-full max-w-3xl rounded-[2rem] bg-cream p-5 shadow-2xl sm:p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-maroon/60">{t.languages}</div><h2 className="mt-1 font-display text-3xl text-maroon">{t.languageTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ink/55">{t.languageSub}</p></div><button onClick={()=>setOpen(false)} className="rounded-full p-2 text-maroon hover:bg-maroon/5" aria-label="Close"><X size={18}/></button></div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">{languages.map((item)=>{const selected=item.code===language;return <button key={item.code} onClick={()=>choose(item.code)} className={`flex items-center justify-between rounded-2xl border px-4 py-3 text-left transition hover:-translate-y-0.5 hover:shadow-card ${selected?'border-maroon bg-maroon text-white':'border-maroon/10 bg-white text-ink/75'}`}><span><span className="block text-sm font-bold">{item.native}</span><span className={`text-[11px] ${selected?'text-white/65':'text-ink/45'}`}>{item.name}</span></span>{selected&&<Check size={16}/>}</button>})}</div><div className="mt-5 rounded-2xl bg-white/70 p-4 text-xs leading-5 text-ink/55"><b>{t.sourceNote}</b></div></div></div>}
    {onboarding&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-ink/35 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-[2rem] bg-cream p-7 shadow-2xl sm:p-9"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-maroon/60"><Globe2 size={14}/> {t.atlas}</div><h2 className="mt-3 font-display text-4xl text-maroon">{t.onboardingTitle}</h2><p className="mt-3 text-sm leading-6 text-ink/55">{t.onboardingBody}</p><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3">{languages.slice(0,12).map(item=><button key={item.code} onClick={()=>choose(item.code)} className="rounded-2xl border border-maroon/10 bg-white px-4 py-3 text-left hover:-translate-y-0.5 hover:shadow-card"><div className="text-sm font-bold text-maroon">{item.native}</div><div className="text-[11px] text-ink/45">{item.name}</div></button>)}</div></div></div>}
  </>
}
